# Generated by Django 5.1.5 on 2025-01-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
